### ISSUE TITLE
Tomcat has an EnvironmentPropertySource, add a K8s Binding Spec Property Source

### ISSUE THREAD

**Issue by dmikusa-pivotal** [paketo-buildpacks/apache-tomcat#205]
Tomcat has an EnvironmentPropertySource which is used for referencing env variables from within Tomcat configuration files. This is handy as you can reference Kubernetes secrets mapped to env variables or other env variable values.

It would also be handy if there was a PropertySource implementation for the K8s Binding specification. This issue is to track submitting such a property source to the upstream Tomcat project for inclusion. If that cannot be done or upstream will not accept the change, then we will publish similar to the access log support or lifecycle support JARs.

**Comment by garethjevans** [comment]
@dmikusa-pivotal was there any feedback from "tomcat" about this? We have a POC internally that we'd like to contribute

**Comment by dmikusa-pivotal** [comment]
I could not get an absolute yes/no because it'll come down to a community vote. It seems like a reasonable request though so I think we should go ahead and give it a try.

Are you planning to submit what you have directly to the Tomcat project?

**Comment by garethjevans** [comment]
Hi @dmikusa-pivotal, the more I think about this, the more I think that its better placed in the Tomcat/Tomee buildpack rather than directly into Tomcat itself.  My rational for this is that to support all existing versions of Tomcat we would need to have the change ported across into each release branch (for 8/9 & 10) (I'm assuming Tomcat are no longer accepting new features for older releases of Tomcat?).

When it comes to Tomee, looking at the [releases/downloads](https://tomee.apache.org/download.html) page, they have not cut a release of Tomee 7 or 9 for sometime

**Comment by garethjevans** [comment]
Yeah, we have an implementation for this, we'll get some PRs created tomorrow and see what the feedback is

**Comment by dmikusa-pivotal** [comment]
This is now included in Tomcat 9.0.63+.
