### ISSUE TITLE
BP_TOMCAT_EXT_CONF_URI should support local dir (relative) paths for external configuration files

### ISSUE THREAD

**Issue by sunetrak** [paketo-buildpacks/apache-tomcat#66]
## What happened?

* What were you attempting to do?
I was attempting to build image with external configuration files in local file system
* What did you expect to happen?
It should take that path and build image
* What was the actual behavior? Please provide log output, if possible.
No buildpack groups passed detection.
## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack 0.14.2+git-0fd189d.build-1450
* What buildpacks are you using? Please include versions.
--builder gcr.io/paketo-buildpacks/builder:base
* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
Thanks for the feedback. 

The biggest challenge here is that when the buildpack runs, it doesn't have access to your local file system. It's running isolated in a container, so we support a URI to access the configuration, as the network is a convenient way to accomplish this. 

I'm not against supporting other methods, but can you elaborate on how you see this working? How would you want to provide these files to the buildpacks from your local file system? Perhaps include an example `pack build ...` command showing what you'd like to see supported.

Thanks

**Comment by dmikusa-pivotal** [comment]
We have made changes to libpak that support this now for all artifacts, including Tomcat external config artifacts. You may use `file://` URLs. This does have limitations though because you can only reference files that are within the builder container when your application runs. Where this can become useful is if you volume mount local files/folders into your builder container (or possibly if you were to package configuration in the builder, however, that's not exactly east at the moment).

For example `pack build --volume $PWD/config:/tomcat -e BP_TOMCAT_EXT_CONF_URI=file:///tomcat/conf.tgz ...`.
